title: Asher Preska Steinberg
url: "https://apsteinberg.github.io"
#for local builds comment out the baseurl line ...
#type "jekyll serve" in terminal
#baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

google_verify: Se1P2nHT1NjVzrgGjkdXozGIqL7gEGUUoHj6ggj3p-o

tracking_id: #

footer: yes
footer_url: "https://github.com/bk2dcradle/researcher"
footer_text: "Page layout designed by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/apsteinberg.github.io/"
 - name: "CV"
   link: "20201231_Asher_CV.pdf"
# - name: "Contact"
#   link: "contact"
