title: Asher Preska Steinberg
url: "https://apsteinberg.github.io"
#for local builds comment out the baseurl line ...
#type "jekyll serve" in terminal
#baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/bk2dcradle/researcher"
footer_text: "Page layout designed by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/apsteinberg.github.io/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
